'use server';

import { generateText } from 'ai';
import { createAzure } from '@ai-sdk/azure';
import { claudeCode } from 'ai-sdk-provider-claude-code';
import { compileSpecStream } from '@json-render/core';
import { catalog } from './Catalog';
import { createMockUI, type GeneratedUISpec, type GeneratedUIResult } from './MockGenerativeUI';

function parseSpec(text: string): GeneratedUISpec {
	const raw = compileSpecStream<GeneratedUISpec>(text);
	// Models routinely omit `children`/`visible` on elements that just use the
	// defaults (no children, always visible); the catalog schema requires both.
	const elements = Object.fromEntries(
		Object.entries(raw.elements).map(([key, element]) => [
			key,
			{ ...element, children: element.children ?? [], visible: element.visible ?? true },
		])
	);
	const spec = { ...raw, elements };

	const validation = catalog.validate(spec);
	if (!validation.success) {
		throw new Error(`Model produced an invalid UI specification: ${validation.error?.message}`);
	}
	return spec;
}


async function createAzureUI(prompt: string): Promise<GeneratedUIResult> {
	const azure = createAzure({
		resourceName: process.env.AZURE_RESOURCE_NAME,
		apiKey: process.env.AZURE_API_KEY,
	});
	const result = await generateText({
		model: azure(process.env.AZURE_MODEL ?? 'gpt-4o-mini'),
		system: catalog.prompt(),
		prompt: `Create a UI for this request: ${prompt}`,
	});

	return {
		spec: parseSpec(result.text),
		source: 'azure',
		summary: 'Generated by the configured Azure model',
	};
}

async function createClaudeUI(prompt: string): Promise<GeneratedUIResult> {
	const result = await generateText({
		model: claudeCode(process.env.ANTHROPIC_MODEL ?? 'sonnet'),
		system: catalog.prompt(),
		prompt: `Create a UI for this request: ${prompt}`,
	});

	return {
		spec: parseSpec(result.text),
		source: 'anthropic',
		summary: 'Generated by Claude via the local Claude Code CLI session',
	};
}

export async function createUI(prompt: string): Promise<GeneratedUIResult> {
	if (!prompt.trim()) {
		throw new Error('Enter a prompt before creating an interface.');
	}

	if (process.env.GENERATIVE_UI_USE_MOCKS !== 'false') {
		await new Promise((resolve) => setTimeout(resolve, 450));
		return createMockUI(prompt);
	}

	if (process.env.AZURE_RESOURCE_NAME && process.env.AZURE_API_KEY) {
		return createAzureUI(prompt);
	}

	return createClaudeUI(prompt);
}
