'use server';

import { generateText, Output } from 'ai';
import { createAzure } from '@ai-sdk/azure';
import { z } from 'zod';
import { catalog } from './Catalog';
import { createMockUI, type GeneratedUIResult } from './MockGenerativeUI';

const uiSpecSchema = z.object({
	root: z.string(),
	elements: z.record(z.string(), z.object({
		type: z.string(),
		props: z.record(z.string(), z.unknown()),
		children: z.array(z.string()).optional(),
	})),
});


async function createAzureUI(prompt: string): Promise<GeneratedUIResult> {
	const azure = createAzure({
		resourceName: process.env.AZURE_RESOURCE_NAME,
		apiKey: process.env.AZURE_API_KEY,
	});
	const result = await generateText({
		model: azure(process.env.AZURE_MODEL ?? 'gpt-4o-mini'),
		system: catalog.prompt(),
		prompt: `Create a UI for this request: ${prompt}`,
		output: Output.object({ schema: uiSpecSchema }),
	});

	return {
		spec: result.output,
		source: 'azure',
		summary: 'Generated by the configured Azure model',
	};
}

export async function createUI(prompt: string): Promise<GeneratedUIResult> {
	if (!prompt.trim()) {
		throw new Error('Enter a prompt before creating an interface.');
	}

	if (process.env.GENERATIVE_UI_USE_MOCKS !== 'false') {
		await new Promise((resolve) => setTimeout(resolve, 450));
		return createMockUI(prompt);
	}

	if (!process.env.AZURE_RESOURCE_NAME || !process.env.AZURE_API_KEY) {
		throw new Error('Live generation requires AZURE_RESOURCE_NAME and AZURE_API_KEY.');
	}

	return createAzureUI(prompt);
}
